from sense_emu import SenseHat
from pygame import mixer
from time import sleep
from gtts import gTTS
import sys
import os

# plays audio files (can get interrupted)
def playAudioFile(filename,repeat):
    mixer.init()
    mixer.music.load(filename)
    mixer.music.play(repeat,0.0)

# plays audio files without them being interrupted
def playAudioFileNoInterruption(filename):
    mixer.init()
    mixer.music.load(filename)
    mixer.music.play()

    while mixer.music.get_busy() == True:
        pass

# uses gtts to " speak "
def text2speech(text):
    filename = 'audio.mp3'
    tts = gTTS(text = text, lang = "en")

    # the audio.mp3 file will get deleted after
    # the intro and various boss sequences
    tts.save(filename)

    playAudioFile(filename,0)

# checks if the player is on the position as the boss
def checkPosition(player,boss):
    if player.x == boss.x:
        if player.y == boss.y:
            return True
    return False

# shows the health of the entity on the sense hat matrix
def showHealth(entity, sense):
    sense.set_pixels(entity.getHealth())

# prints text on the terminal emulating old video games
# the delay serves to try and synchronize the text2speech
# to the text being printed on the terminal
def myPrint(text, delay):
    text = text.split()
    for word in text:
        sys.stdout.write(word + " ")
        sleep(delay)
    sys.stdout.write("\n")

# intro sequence
def intro():
    text2speech("Bowser and his firends have kidnapped the princess!You must go and save her!")
    myPrint("Toad: Bowser and his firends have kidnapped the princess!",0.6)
    myPrint("Toad: You must go and save her!",0.3)
    os.remove("audio.mp3") # deletes the audio.mp3 file generated by text2speech

# boss sequance
def bowser():
    text2speech("Hear this! I will kidnap the princess over and over until I pull it off! And no one can stop me! Losing is not an option! And neither is giving up!")
    myPrint("Bowser: Hear this!",0.4)
    myPrint("Bowser: I will kidnap the princess over and over until I pull it off!",0.4)
    myPrint("Bowser: And no one can stop me! Losing is not an option!",0.4)
    myPrint("Bowser: And neither is giving up!",0.3)
    os.remove("audio.mp3") # deletes the audio.mp3 file generated by text2speech

# boss sequance
def cackletta():
    text2speech("Hahahahahaa! Well won't this be fun! Oh yes! If that's how it is I'm ready for you! I'm going to knock you all the way back to your Kingdom!")
    myPrint("Cackletta: Hahahahahaa!",0.6)
    myPrint("Cackletta: Well won't this be fun!Oh yes!",0.4)
    myPrint("Cackletta: If that's how it is I'm ready for you!",0.3)
    myPrint("Cackletta: I'm going to knock you all the way back to your Kingdom!",0.3)
    os.remove("audio.mp3") # deletes the audio.mp3 file generated by text2speech

# boss sequance
def bowletta():
    text2speech("My new country has no need for old superstars! It will do just fine with only one: the Great Bowletta!!!")
    myPrint("Bowletta: My new country has no need for old superstars!",0.4)
    myPrint("Bowletta: It will do just fine with only one: the Great Bowletta!!!",0.4)
    os.remove("audio.mp3") # deletes the audio.mp3 file generated by text2speech

# the credits will only be shown on the terminal
# because I wanted the music to be there at the same time
def credits():
    # plays credits music for 15 seconds
    playAudioFile("music/credits.mp3",-1)

    myPrint("Congratulations! You managed to save the princess!",0.5)
    myPrint("The Player and the princess returned to their kingdom and lived a happy life.",0.5)
    sleep(15)
    mixer.music.stop() # stops the music

# fight will be called at each boss encounter
def fight(player, boss, sense):

    # plays boss music
    playAudioFile("music/boss.mp3",-1)
    playerTurn = True

    showHealth(player,sense)
    while(boss.isAlive()):

        if playerTurn:
            # player chooses what to do on the terminal
            if player.playerTurn() == 1: 
                showHealth(boss,sense)
                sleep(0.4)
                player.attack(boss)
                showHealth(boss,sense)
                sleep(0.4)
                print("You attacked ", boss.name, ".")
            else:
                player.drink_potion()
                showHealth(player,sense)
                sleep(1)

            playerTurn = False

        else:
            showHealth(player,sense)
            sleep(0.4)
            boss.attack(player)
            showHealth(player,sense)
            print(boss.name,"attacked you.")
            playerTurn = True

        if player.isAlive() == False:
            # plays game over music
            playAudioFileNoInterruption('music/game_over.mp3')
            print("Game over")
            return False

    # plays victory music
    playAudioFileNoInterruption('music/victory.mp3')
    print(boss.name," was defeated")
    player.level_up()

    return True
 